plugins {
    alias(libs.plugins.android.application)
    id("com.google.gms.google-services")
}

android {
    namespace 'com.example.everythingbim'
    compileSdk = 36

    
    defaultConfig {
        applicationId "com.example.everythingbim"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "ML_API_BASE_URL", "\"http://10.0.2.2:8000\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
        dataBinding true
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    androidResources {
        noCompress += 'tflite'
    }
}

dependencies {

    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation libs.appcompat
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.auth
    implementation libs.firebase.firestore
    implementation libs.firebase.storage
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1' // optional for user location
    implementation 'com.google.android.libraries.places:places:3.5.0'
    implementation 'com.google.android.gms:play-services-tasks:18.4.1'
    implementation 'org.tensorflow:tensorflow-lite:2.17.0'
    implementation "androidx.room:room-runtime:2.6.0"
    annotationProcessor "androidx.room:room-compiler:2.6.0"
    implementation libs.glide
}
